language: node_js
node_js: stable
# 缓存依赖
cache:  
  directories:
    - node_modules
    - $HOME/.npm

notifications:
  email:
    recipients:
      - youdng@hotmail.com # 设置通知邮件
    on_success: change
    on_failure: always

before_install:
  - export TZ='Asia/Shanghai' # 更改时区
# 依赖安装
install:
  - npm install -g gitbook-cli
  - gitbook install   # 安装 gitbook 插件

script:
  - gitbook build ./gitbook ./docs  # 自定义输出目录 gitbook build src dest

branches:
  only:
    - master  #只监测master分支

# GitHub Pages 部署
deploy:
  provider: pages
  skip_cleanup: true
    # 在项目仪表盘的 Settings -> Environment Variables 中配置
  github_token: $GITHUB_TOKEN
    # 将 build 目录下的内容推送到默认的 gh-pages 分支上，并不会连带 build 目录一起
  local_dir: docs
    #fqdn: $CUSTOM_DOMAIN
  name: $GIT_NAME
  email: $GIT_EMAIL
  on:
    branch: master