name: 'auto-publish-gitbook'
on:                                 #在master分支上进行push时触发  
  push:
    branches:
    - master

jobs:
  master-to-gh-pages:
    runs-on: ubuntu-latest
        
    steps:                          
    - name: checkout master
      uses: actions/checkout@v3
      with:
        ref: master
            
    - name: install nodejs
      uses: actions/setup-node@v3
      with:
          node-version: '10.22.0'
      
    - name: configue gitbook
      run: |
        npm install -g gitbook-cli          
        gitbook install
                
    - name: generate _book folder
      run: |
        gitbook build
                
    - name: push _book to branch gh-pages 
      env:
        TOKEN: ${{ secrets.GitBook }}
        REF: github.com/${{github.repository}}
        MYEMAIL: youdng@hotmail.com                  # 记得修改为自己github设置的邮箱！！
        MYNAME: ${{github.repository_owner}}          
      run: |
        cd _book
        git config --global user.email "${MYEMAIL}"
        git config --global user.name "${MYNAME}"
        git init
        git remote add origin https://${REF}
        git checkout -b gh-pages
        git add . 
        git commit -m "Updated By Github Actions With Build ${{github.run_number}} of ${{github.workflow}} For Github Pages"
        git push --force --quiet "https://${TOKEN}@${REF}" gh-pages